name: release

on:
  - push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "dev@jerrywithaz.com"

      - name: Install Packages
        run: yarn install --frozen-lockfile

      - name: Test
        shell: bash
        run: yarn nx run workspace:test

      - name: Lint
        shell: bash
        run: yarn nx run workspace:lint

      - name: Version
        shell: bash
        run: yarn nx run workspace:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}